# Generated by Django 3.1.3 on 2020-11-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledeveloper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.developer', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='profileadministrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.administrator', verbose_name='Usuario'),
        ),
    ]
