# Generated by Django 3.1.3 on 2020-11-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='developer',
            field=models.ManyToManyField(to='users.Developer'),
        ),
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.typetask'),
        ),
    ]
