# Generated by Django 3.1.3 on 2020-11-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_developer'),
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='developer',
            field=models.ManyToManyField(to='users.Developer', verbose_name='Desarrollador'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.typetask', verbose_name='Tipo Tarea'),
        ),
        migrations.AddField(
            model_name='activities',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
