# Generated by Django 3.1.3 on 2020-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201127_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='process',
            field=models.BooleanField(default=False),
        ),
    ]
