# Generated by Django 3.1.3 on 2020-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201109_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='activities',
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('task', models.ManyToManyField(to='tasks.Task')),
            ],
        ),
    ]
