# Generated by Django 3.1.3 on 2020-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201123_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetask',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
