# Generated by Django 3.1.3 on 2020-11-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201111_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='activities',
        ),
        migrations.AddField(
            model_name='activities',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
            preserve_default=False,
        ),
    ]
