# Generated by Django 3.1.3 on 2020-11-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dates', '0001_initial'),
        ('users', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.developer'),
        ),
        migrations.AddField(
            model_name='date',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
